### 注意 JOSN 结尾 不能 有逗号！！
### get all persons
GET http://localhost:3001/api/persons

### get info
GET http://localhost:3001/api/persons/info

### get by id
GET http://localhost:3001/api/persons/5f01e1a9

### delete by id
DELETE http://localhost:3001/api/persons/5f020ea9eabe31bd453349df

### create a new one, or duplicate
PUT http://localhost:3001/api/persons/5f01e1a9d721d8b6469d1b05
Content-Type: application/json

{
    "name": "rw",
    "number": {{$randomInt 10 200}}
}
### create a new one, or duplicate
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test one",
    "number": {{$randomInt 10 200}}
}


### create but missing name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": 881230
}

### create but missing number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test one",
    "number": ""
}

### unkonwnEndpoint
POST http://localhost:3001/api/personss
Content-Type: application/json

{
    "name": "test one",
    "number": ""
}

### get all blog
GET http://localhost:3001/api/blogs

### post a blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Games2",
    "author":"leihao0",
    "url":"https://leihao0.github.io/Games/",
    "likes":"2"
}

### register a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username":"Panda1",
    "name":"panda",
    "password":"panda_no_1"
}

### login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Panda1",
    "password": "panda_no_1"
}

